#' Generate a Predictive Plot with Confidence Intervals
#'
#' This function generates a ggplot-based visualization for a generalized additive model (GAM),
#' including predictions and confidence intervals. It also returns the processed data used in the plot.
#'
#' @param modelo A GAM model object generated by `mgcv::gam()`. Default is `m`.
#' @param exclude A character vector specifying terms, average across random effects, from the model matrix during prediction.
#'                Defaults to `"s(Year,Stnumber)"`.
#' @param varX A character string specifying the name of the variable for the x-axis. Default is `"Year"`. Must be the same name as the variable in the dataframe used for the fit.
#' @param ylab A character string for the y-axis label. Default is `"ylab"`.
#' @param legenTitle A character string for the legend title. Default is `"legenTitle"`.
#' @param name A character string for the plot title. Default is `"Plot Name"`.
#'
#' @return A list containing:
#'   \describe{
#'     \item{d}{A data frame with the original and predicted values, along with confidence intervals.}
#'     \item{grafico}{A ggplot object representing the predictive plot.}
#'   }
#'
#' @details
#' The function uses the `mgcv::predict.gam()` function to calculate predictions and confidence intervals 
#' for a GAM model. It supports excluding (average across random effects) specific terms from the model matrix during prediction. 
#' The visualization is built with `ggplot2` and includes a line for predictions, a shaded ribbon for confidence intervals, 
#' and customized colors for groups in the data.
#'
#' @examples
#' # Assuming `modelo` is a fitted GAM object:
#' result <- plotgraf(modelo = modelo, exclude = c("s(Year,Stnumber)"), varX = "Year")
#' print(result$grafico)
#' 
#' @import ggplot2
#' @import mgcv
#' @export

plotgraf = function(modelo = m, exclude = "s(Year,Stnumber)", varX = "Year",
                    ylab = "ylab", legenTitle = "ylab", name = "Plot Name"){
  
  # Load necessary libraries
  library(ggplot2)
  library(mgcv)
  
  # Extract the dataset used in the GAM model
  d = modelo$model 
  
  # Extract the values of the variable specified by varX
  x = d[, which(colnames(d) == paste(varX))]
  
  # Check if exclude has two elements to handle multiple exclusions
  if (length(exclude) == 2) {
    
    # Generate the linear predictor matrix excluding specific terms
    xp = predict.gam(modelo, type = "lpmatrix", exclude = list(exclude[1], exclude[2]))
    
    # Calculate predicted values
    yhat = xp %*% coef(modelo)
    
    # Compute standard errors, critical t-value, and confidence intervals
    se <- sqrt(rowSums((xp %*% vcov(modelo)) * xp))
    crit <- qt(.975, df.residual(modelo))
    upr <- yhat + (crit * se)
    lwr <- yhat - (crit * se)
    
    # Add predictions and confidence intervals to the dataset
    d$yhat = yhat
    d$upr = upr
    d$lwr = lwr
    
    # Create the ggplot object for visualization
    graf = ggplot(d, aes(x, yhat, colour = Impacted)) +
      geom_line() + 
      geom_ribbon(aes(ymin = lwr, ymax = upr), fill = "grey70", alpha = 0.2, linetype = 0) +
      ylab(ylab) + 
      xlab(varX) + 
      ggtitle(paste(name)) +
      scale_color_manual(values = c("#00BCD8", "#F8766D")) +
      guides(colour = guide_legend(title = paste(legenTitle), override.aes = list(size = 1))) +
      theme(plot.title = element_text(hjust = 0.5))
    
    # Create a new dataset for returning, including predictions and intervals
    d = data.frame(
      Year = d$Year, 
      Impacted = d$Impacted, 
      Stnumber = d$Stnumber, 
      y = d$y, 
      yhat = d$yhat, 
      se = se, 
      upr = d$upr, 
      lwr = d$lwr
    )
    
    # Return the dataset and the plot as a list
    l = list(d = d, grafico = graf)
  } else {
    # For cases where exclude has only one term
    
    # Generate the linear predictor matrix excluding specific terms
    xp = predict.gam(modelo, type = "lpmatrix", exclude = list(exclude))
    
    # Calculate predicted values
    yhat = xp %*% coef(modelo)
    
    # Compute standard errors, critical t-value, and confidence intervals
    se <- sqrt(rowSums((xp %*% vcov(modelo)) * xp))
    crit <- qt(.975, df.residual(modelo))
    upr <- yhat + (crit * se)
    lwr <- yhat - (crit * se)
    
    # Add predictions and confidence intervals to the dataset
    d$yhat = yhat
    d$upr = upr
    d$lwr = lwr
    
    # Create the ggplot object for visualization
    graf = ggplot(d, aes(x, yhat, colour = Impacted)) +
      geom_line() + 
      geom_ribbon(aes(ymin = lwr, ymax = upr), fill = "grey70", alpha = 0.5, linetype = 0) +
      ylab(paste(ylab)) + 
      xlab(varX) + 
      ggtitle(paste(name)) +
      scale_color_manual(values = c("#00BCD8", "#F8766D")) +
      guides(colour = guide_legend(title = paste(legenTitle), override.aes = list(size = 1))) +
      theme(plot.title = element_text(hjust = 0.5))
    
    # Create a new dataset for returning, including predictions and intervals
    d = data.frame(
      Year = d$Year, 
      Impacted = d$Impacted, 
      Stnumber = d$Stnumber, 
      y = d$y, 
      yhat = d$yhat, 
      se = se, 
      upr = d$upr, 
      lwr = d$lwr
    )
    
    # Return the dataset and the plot as a list
    l = list(d = d, grafico = graf)
  }
  
  # Return the final list
  l
}
